version: '3.8'  # (opcional, mas recomendado)

services:

  parking_service:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - parking_db
      - rabbitmq
    environment:
      - DB_NAME=parking_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=parking_db
# Você pode adicionar volumes aqui se quiser mapear o código local (ex: volumes: ['./:/app'])

  worker:
    build: .
    command: celery -A core worker -l INFO
    restart: always
    depends_on:
      - parking_db
      - rabbitmq

  parking_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking_service

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq-data: